import type { Pillar, Tile, TileGroup } from '../engine/types.js';

/**
 * Cajas del mapa de Microsoft 365 Business Premium (m365maps.com), en el mismo orden visual.
 * `pillar` indica cuál de los cuatro pilares de gobierno (Entra ID, Intune, Defender, Purview)
 * la gobierna; las cajas sin pilar son capacidades de productividad incluidas en la licencia.
 */
const t = (id: string, name: string, group: TileGroup, description: string, pillar?: Pillar): Tile => ({
  id,
  name,
  group,
  description,
  pillar,
});

export const TILES: Tile[] = [
  // ---------------- Office 365 ----------------
  t('activity-reports', 'Activity Reports', 'office365', 'Informes de uso de Exchange, Teams, SharePoint y OneDrive en el centro de administración.', 'purview'),
  t('adoption-score', 'Adoption Score', 'office365', 'Mide cómo la organización adopta las herramientas de colaboración y la experiencia tecnológica.'),
  t('alert-policies', 'Alert Policies', 'office365', 'Alertas predefinidas ante actividad sospechosa (reenvíos masivos, permisos elevados, malware).', 'purview'),
  t('audit-standard', 'Audit (standard)', 'office365', 'Registro de auditoría unificado con 180 días de retención de actividades de usuarios y administradores.', 'purview'),
  t('basic-mobility-security', 'Basic Mobility & Security', 'office365', 'MDM básico integrado en Office 365. Con Business Premium se reemplaza por Intune.', 'intune'),
  t('bookings', 'Bookings', 'office365', 'Agenda de citas en línea para clientes, integrada con Outlook y Teams.'),
  t('clipchamp', 'Clipchamp Standard', 'office365', 'Editor de video para comunicaciones internas y marketing.'),
  t('compliance-manager', 'Compliance Manager', 'office365', 'Evalúa el cumplimiento frente a normas (ISO 27001, Ley de protección de datos) con acciones de mejora.', 'purview'),
  t('content-search', 'Content Search', 'office365', 'Búsqueda de contenido en buzones, sitios y Teams para investigaciones.', 'purview'),
  t('dataverse-teams', 'Dataverse for Teams', 'office365', 'Base de datos de bajo código dentro de Teams para apps de Power Platform.'),
  t('dlp', 'Data Loss Prevention', 'office365', 'Detecta y bloquea el envío de datos sensibles (RUT, tarjetas) fuera de la empresa.', 'purview'),
  t('ediscovery-standard', 'eDiscovery (standard)', 'office365', 'Casos, retenciones legales y exportación de contenido para requerimientos legales.', 'purview'),
  t('exchange-online-archiving', 'Exchange Online Archiving', 'office365', 'Buzón de archivo y retención de correo a largo plazo.', 'purview'),
  t('exchange-online', 'Exchange Online Plan 1+', 'office365', 'Correo corporativo de 50 GB. Su configuración segura es clave contra fraude por correo.', 'defender'),
  t('graph-connector', 'Graph Connector Capacity', 'office365', 'Indexa fuentes externas en Microsoft Search y Copilot.'),
  t('information-protection-m365', 'Information Protection for M365', 'office365', 'Etiquetas de confidencialidad manuales en Office, Outlook y Teams.', 'purview'),
  t('loop-workspaces', 'Loop Workspaces', 'office365', 'Espacios colaborativos con componentes Loop. Se rigen por las reglas de uso compartido de SharePoint.', 'purview'),
  t('message-encryption', 'Message Encryption (basic)', 'office365', 'Cifrado de correos para cualquier destinatario.', 'purview'),
  t('m365-apps-business', 'Microsoft 365 Apps for Business (with SCA)', 'office365', 'Word, Excel, PowerPoint y Outlook de escritorio, con activación en equipos compartidos.'),
  t('copilot-basic', 'Microsoft 365 Copilot (Basic)', 'office365', 'Copilot Chat con protección de datos empresariales. Las etiquetas y permisos definen qué puede ver.'),
  t('m365-mobile-app', 'Microsoft 365 Mobile App', 'office365', 'Apps móviles de Office; se protegen con políticas de protección de aplicaciones (MAM).', 'intune'),
  t('forms', 'Microsoft Forms', 'office365', 'Formularios y encuestas.'),
  t('lists', 'Microsoft Lists', 'office365', 'Listas para seguimiento de información.'),
  t('places', 'Microsoft Places (core)', 'office365', 'Coordinación de trabajo híbrido y presencia en la oficina.'),
  t('search', 'Microsoft Search', 'office365', 'Búsqueda unificada en todo Microsoft 365.'),
  t('todo', 'Microsoft To Do', 'office365', 'Gestión de tareas personales.'),
  t('whiteboard', 'Microsoft Whiteboard', 'office365', 'Pizarra colaborativa.'),
  t('office-web', 'Office for the Web', 'office365', 'Office en el navegador.'),
  t('onedrive', 'OneDrive Plan 1', 'office365', '1 TB por usuario. Controla uso compartido externo y sincronización.', 'purview'),
  t('planner', 'Planner for Office 365', 'office365', 'Planificación de tareas en equipo.'),
  t('power-apps', 'Power Apps for Office 365', 'office365', 'Aplicaciones de bajo código sobre datos de Microsoft 365.'),
  t('power-automate', 'Power Automate for Office 365', 'office365', 'Flujos de automatización con conectores estándar.'),
  t('project-roadmap', 'Project & Roadmap View Access', 'office365', 'Visualización de proyectos.'),
  t('secure-score', 'Secure Score', 'office365', 'Puntaje de seguridad del tenant con acciones recomendadas. Lo usa el Assessment.', 'defender'),
  t('sharepoint-online', 'SharePoint Online Plan 1', 'office365', 'Intranet y documentos. El uso compartido externo se gobierna a nivel de tenant.', 'purview'),
  t('sway', 'Sway', 'office365', 'Presentaciones interactivas.'),
  t('teams-essentials', 'Teams Essentials (optional)', 'office365', 'Reuniones, chat y colaboración. Hereda gobierno de grupos, etiquetas y uso compartido.', 'purview'),
  t('teams-webinars', 'Teams Webinars', 'office365', 'Seminarios web con registro.'),
  t('visio-web', 'Visio for the Web', 'office365', 'Diagramas en el navegador.'),
  t('viva-connections', 'Viva Connections', 'office365', 'Portal del empleado en Teams.'),
  t('viva-engage', 'Viva Engage', 'office365', 'Red social corporativa.'),
  t('viva-insights', 'Viva Insights - Personal (basic)', 'office365', 'Hábitos de trabajo y bienestar personal.'),
  t('viva-learning', 'Viva Learning (basic)', 'office365', 'Contenidos de aprendizaje en Teams.'),
  // Defender for Office 365 Plan 1
  t('advanced-anti-phishing', 'Advanced Anti-Phishing', 'defender-o365', 'Protección contra suplantación de ejecutivos y dominios con inteligencia de buzón.', 'defender'),
  t('exchange-online-protection', 'Exchange Online Protection', 'defender-o365', 'Filtro antispam y antimalware base, reenvío externo y autenticación de correo (DKIM).', 'defender'),
  t('real-time-reports', 'Real-Time Reports', 'defender-o365', 'Explorador en tiempo real de amenazas por correo.', 'defender'),
  t('safe-attachments', 'Safe Attachments', 'defender-o365', 'Detonación de adjuntos en sandbox antes de entregarlos.', 'defender'),
  t('safe-links', 'Safe Links', 'defender-o365', 'Análisis de enlaces en el momento del clic.', 'defender'),

  // ---------------- EMS: Entra ID P1 ----------------
  t('administrative-units', 'Administrative Units', 'entra-p1', 'Delegar administración por área o sucursal.', 'entra'),
  t('advanced-security-reports', 'Advanced Security Reports & Alerts', 'entra-p1', 'Informes de inicios de sesión riesgosos y actividad anómala.', 'entra'),
  t('agent-id', 'Agent ID', 'entra-p1', 'Identidades para agentes de IA gobernadas como cualquier otra identidad.', 'entra'),
  t('app-proxy', 'App Proxy (including PingAccess)', 'entra-p1', 'Publica aplicaciones web internas con inicio de sesión de Entra ID, sin VPN.', 'entra'),
  t('cloud-app-discovery', 'Cloud App Discovery', 'entra-p1', 'Descubre qué aplicaciones SaaS usa la empresa (shadow IT).', 'entra'),
  t('conditional-access', 'Conditional Access', 'entra-p1', 'El motor de Zero Trust: decide quién accede, desde dónde y con qué dispositivo.', 'entra'),
  t('custom-security-attributes', 'Custom Security Attributes', 'entra-p1', 'Atributos propios para clasificar usuarios y aplicaciones.', 'entra'),
  t('customized-sign-in', 'Customized Sign-in Page', 'entra-p1', 'Personaliza la página de inicio de sesión con la marca de la empresa.', 'entra'),
  t('dynamic-groups', 'Dynamic Groups', 'entra-p1', 'Grupos cuyos miembros se calculan por reglas (área, sistema operativo, etc.).', 'entra'),
  t('enterprise-state-roaming', 'Enterprise State Roaming', 'entra-p1', 'Sincroniza la configuración de Windows entre equipos corporativos.', 'entra'),
  t('connect-health', 'Entra ID Connect Health', 'entra-p1', 'Monitoreo de la sincronización con Active Directory local.', 'entra'),
  t('internet-access-microsoft', 'Entra Internet Access for Microsoft', 'entra-p1', 'Acceso seguro al tráfico de Microsoft 365 (Global Secure Access).', 'entra'),
  t('external-id', 'External ID', 'entra-p1', 'Colaboración con invitados (B2B).', 'entra'),
  t('mim', 'Microsoft Identity Manager', 'entra-p1', 'Sincronización de identidades en escenarios locales complejos.', 'entra'),
  t('mfa', 'Multi-Factor Auth (MFA)', 'entra-p1', 'Segundo factor de autenticación: la medida de seguridad más efectiva.', 'entra'),
  t('password-protection', 'Password Protection', 'entra-p1', 'Bloquea contraseñas débiles o con palabras de la empresa.', 'entra'),
  t('passwordless', 'Passwordless Authentication', 'entra-p1', 'Passkeys, FIDO2 y Windows Hello: sin contraseñas que robar.', 'entra'),
  t('self-service-group-management', 'Self-Service Group Management', 'entra-p1', 'Qué pueden crear los usuarios: grupos, Teams, apps e invitados.', 'entra'),
  t('sspr', 'Self-Service Password Reset in AD', 'entra-p1', 'Restablecimiento de contraseña de autoservicio con escritura diferida a AD.', 'entra'),
  t('self-service-activity-reports', 'Self-Service Activity Reports', 'entra-p1', 'Informes de registro y uso de SSPR/MFA.', 'entra'),
  t('sla', 'Service Level Agreement', 'entra-p1', 'SLA de 99,99 % de disponibilidad de autenticación.', 'entra'),
  t('shared-password-rollover', 'Shared Account Password Roll-Over', 'entra-p1', 'Rotación de contraseñas de cuentas compartidas en apps SSO.', 'entra'),
  t('sso-saas', 'Single-Sign-On to other SaaS', 'entra-p1', 'Inicio de sesión único en aplicaciones de terceros y control de consentimiento.', 'entra'),
  t('sms-sign-in', 'SMS Sign-in', 'entra-p1', 'Inicio de sesión con SMS para trabajadores de primera línea. Método débil para MFA.', 'entra'),
  t('temporary-access-pass', 'Temporary Access Pass', 'entra-p1', 'Código temporal para onboarding y recuperación sin contraseña.', 'entra'),
  t('tenant-restrictions', 'Tenant Restrictions', 'entra-p1', 'Impide usar cuentas de otros tenants desde la red corporativa.', 'entra'),
  t('terms-of-use', 'Terms of Use', 'entra-p1', 'Aceptación obligatoria de la política de uso aceptable.', 'entra'),
  t('verified-id', 'Verified ID', 'entra-p1', 'Credenciales verificables (onboarding remoto, verificación de identidad).', 'entra'),
  t('windows-autopilot-ems', 'Windows Autopilot', 'entra-p1', 'Aprovisionamiento de equipos nuevos sin tocar la imagen.', 'intune'),
  t('third-party-mfa', '3rd Party MFA Integration', 'entra-p1', 'Integra proveedores de MFA externos (métodos de autenticación externos).', 'entra'),
  // Intune
  t('application-management', 'Application Management', 'intune-p1', 'Protección de apps (MAM) y despliegue de aplicaciones.', 'intune'),
  t('device-management', 'Device Management', 'intune-p1', 'Inscripción, cumplimiento y configuración de Windows, macOS, iOS y Android.', 'intune'),
  t('endpoint-analytics', 'Endpoint Analytics', 'intune-p1', 'Rendimiento y experiencia de los equipos.', 'intune'),
  t('information-protection', 'Information Protection', 'ems', 'Azure Information Protection P1: etiquetado y cifrado en Office y archivos.', 'purview'),

  // ---------------- Windows Pro ----------------
  t('application-control', 'Application Control', 'windows', 'Solo aplicaciones confiables pueden ejecutarse (App Control for Business).', 'defender'),
  t('applocker', 'AppLocker', 'windows', 'Listas de aplicaciones permitidas/bloqueadas por ruta o editor.', 'defender'),
  t('assigned-access', 'Assigned Access', 'windows', 'Modo quiosco para equipos de uso único.', 'intune'),
  t('bitlocker', 'BitLocker', 'windows', 'Cifrado de disco completo.', 'intune'),
  t('bitlocker-to-go', 'BitLocker to Go', 'windows', 'Cifrado de pendrives y discos externos.', 'intune'),
  t('defender-antivirus', 'Defender Antivirus', 'windows', 'Antivirus integrado en Windows.', 'defender'),
  t('domain-join', 'Domain Join', 'windows', 'Unión a Active Directory local.', 'entra'),
  t('edge-business', 'Edge for Business', 'windows', 'Navegador corporativo con SmartScreen y perfiles de trabajo.', 'intune'),
  t('entra-id-join', 'Entra ID Join', 'windows', 'Unión de equipos a Entra ID (nube).', 'entra'),
  t('laps', 'LAPS', 'windows', 'Contraseña de administrador local única y rotativa.', 'intune'),
  t('manage-by-mdm', 'Manage by MDM', 'windows', 'Administración de Windows por Intune.', 'intune'),
  t('pad-flows', 'Power Automate Attended Desktop Flows', 'windows', 'RPA de escritorio con Power Automate Desktop.'),
  t('unbranded-boot', 'Unbranded Boot', 'windows', 'Oculta elementos de arranque de Windows en quioscos.', 'intune'),
  t('universal-print', 'Universal Print', 'windows', 'Impresión en la nube sin servidores de impresión.', 'intune'),
  t('windows-autopatch', 'Windows Autopatch', 'windows', 'Actualizaciones gestionadas por Microsoft.', 'intune'),
  t('windows-conditional-access', 'Windows Conditional Access', 'windows', 'Acceso condicionado al estado del equipo Windows.', 'entra'),
  t('windows-firewall', 'Windows Firewall', 'windows', 'Firewall de host.', 'intune'),
  t('windows-hello', 'Windows Hello for Business', 'windows', 'PIN/biometría ligados al hardware en lugar de contraseña.', 'intune'),
  t('windows-update-business', 'Windows Update for Business', 'windows', 'Control de anillos y plazos de actualización.', 'intune'),
  t('windows-virtualization', 'Windows Virtualization Rights', 'windows', 'Derechos de uso de Windows en VDI / Windows 365.'),
  t('windows-11-support', '24 months support for Windows 11', 'windows', 'Soporte de 24 meses por versión de Windows 11 Pro.', 'intune'),
  // Defender for Business
  t('attack-surface-reduction', 'Attack Surface Reduction (enhanced)', 'defender-business', 'Reglas que bloquean técnicas de ransomware y macros.', 'defender'),
  t('automated-investigations', 'Automated Investigations', 'defender-business', 'Investigación y remediación automática de alertas.', 'defender'),
  t('block-at-first-sight', 'Block at First Sight', 'defender-business', 'Bloqueo en segundos de malware nunca visto usando la nube.', 'defender'),
  t('centralized-management', 'Centralized Management', 'defender-business', 'Administración unificada en el portal de Defender.', 'defender'),
  t('cross-platform', 'Cross-Platform Support', 'defender-business', 'Protección para Windows, macOS, iOS y Android.', 'defender'),
  t('vulnerability-management', 'Defender Vulnerability Management (core)', 'defender-business', 'Inventario de software y vulnerabilidades priorizadas.', 'defender'),
  t('edr', 'Endpoint Detection & Response', 'defender-business', 'Detección y respuesta: aislar equipos, recolectar evidencias.', 'defender'),
  t('mobile-threat-defence', 'Mobile Threat Defence', 'defender-business', 'Protección antiphishing y de apps en móviles.', 'defender'),
  t('next-gen-protection', 'Next Gen Protection', 'defender-business', 'Antivirus con aprendizaje automático y protección en la nube.', 'defender'),
  t('tamper-protection', 'Tamper Protection', 'defender-business', 'Impide que malware o usuarios desactiven Defender.', 'defender'),
  t('threat-analytics', 'Threat Analytics', 'defender-business', 'Informes de amenazas activas y su exposición.', 'defender'),
  t('web-content-filtering', 'Web Content Filtering', 'defender-business', 'Bloqueo de categorías web.', 'defender'),

  t('fasttrack', 'FastTrack', 'fasttrack', 'Asistencia de Microsoft para el despliegue (150+ licencias).'),
];

export const GROUP_LABELS: Record<TileGroup, string> = {
  office365: 'Office 365',
  'defender-o365': 'Defender for Office 365 Plan 1',
  'entra-p1': 'Entra ID Plan 1',
  'intune-p1': 'Intune Plan 1 for Business',
  ems: 'Enterprise Mobility + Security',
  windows: 'Windows Pro',
  'defender-business': 'Defender for Business',
  fasttrack: 'FastTrack',
};
